FROM php:8.2-fpm-alpine

# Install system dependencies
RUN apk add --no-cache nginx wget supervisor

# Install php extensions
RUN docker-php-ext-install pdo pdo_mysql

# Configure Nginx
RUN mkdir -p /run/nginx
COPY .docker/nginx.conf /etc/nginx/nginx.conf

# Set working directory
WORKDIR /var/www/html
COPY . .

# Install Composer
RUN curl -sS https://getcomposer.org | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader

# Set permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80

CMD ["sh", "-c", "php-fpm -D && nginx -g 'daemon off;'"]